version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: kodened/global-accelerex-api
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=ga-mysql-app
      - MYSQL_USER=gauser
      - MYSQL_PASS=gapass
      - MYSQL_DB=global-accelerex
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:3000"
    container_name: ga-nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=gauser
      - MYSQL_PASSWORD=gapass 
      - MYSQL_DATABASE=global-accelerex
    container_name: ga-mysql-app
  migration:
    image: kodened/global-accelerex-api:latest
    command: ["./wait-for-it/wait-for-it.sh", "mysql:3306", "--", "npm", "run", "migrate:run"]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=ga-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: ga-phpmyadmin-app
networks:
  frontend:
  backend: